# Generated by Django 4.2.1 on 2023-05-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="availability_days",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="subjects",
            field=models.CharField(max_length=255),
        ),
    ]
