# Generated by Django 4.2.1 on 2023-05-19 15:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0002_alter_student_availability_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="availability_days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="subjects",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("English", "English"),
                    ("Math", "Math"),
                    ("Science", "Science"),
                ],
                max_length=255,
            ),
        ),
    ]
